from pathlib import Path
p=Path('worker.js')
s=p.read_text()
if 'async function handleGradedMarket(' in s:
    raise SystemExit('graded route already exists')
marker='async function handleOrders(request, env) {'
if marker not in s:
    raise SystemExit('handleOrders marker missing')
block='''async function browseFetch(env, path) {\n  const token = await getAppAccessToken(env);\n  const res = await fetch(EBAY_API + path, {\n    method: "GET",\n    headers: {\n      "authorization": "Bearer " + token,\n      "accept": "application/json",\n      "accept-language": "en-GB",\n      "x-ebay-c-marketplace-id": "EBAY_GB"\n    }\n  });\n  const text = await res.text();\n  let data = null;\n  if (text) { try { data = JSON.parse(text); } catch { data = { raw: text }; } }\n  return { ok: res.ok, status: res.status, data };\n}\n\nasync function handleGradedMarket(request, env) {\n  let body;\n  try { body = await request.json(); }\n  catch { return json({ ok:false, error:"invalid_json", message:"Request body must be valid JSON." }, 400); }\n\n  const cardName = String(body?.cardName || "").trim();\n  const cardNumber = String(body?.cardNumber || "").trim();\n  const grader = String(body?.grader || "").trim();\n  const grade = String(body?.grade || "").trim();\n  const setName = String(body?.setName || "").trim();\n  const language = String(body?.language || "").trim();\n  const missing = [];\n  if (!cardName) missing.push("cardName");\n  if (!cardNumber) missing.push("cardNumber");\n  if (!grader) missing.push("grader");\n  if (!grade) missing.push("grade");\n  if (missing.length) return json({ ok:false, error:"graded_identity_required", missing }, 400);\n\n  const query = [cardName, cardNumber, grader, grade, language, "Pokemon"].filter(Boolean).join(" ");\n  const params = new URLSearchParams();\n  params.set("q", query);\n  params.set("limit", "50");\n  params.set("filter", "buyingOptions:{FIXED_PRICE}");\n  const ebay = await browseFetch(env, "/buy/browse/v1/item_summary/search?" + params.toString());\n  if (!ebay.ok) {\n    return json({ ok:false, error:"ebay_browse_failed", status:ebay.status, message:"eBay current-listing search failed.", data:ebay.data }, ebay.status || 502);\n  }\n\n  const itemSummaries = Array.isArray(ebay.data?.itemSummaries) ? ebay.data.itemSummaries.map(x => ({\n    itemId: String(x?.itemId || ""),\n    title: String(x?.title || ""),\n    price: x?.price || null,\n    itemWebUrl: String(x?.itemWebUrl || ""),\n    condition: String(x?.condition || ""),\n    buyingOptions: Array.isArray(x?.buyingOptions) ? x.buyingOptions : [],\n    seller: x?.seller ? { username: String(x.seller.username || ""), feedbackPercentage: String(x.seller.feedbackPercentage || "") } : null,\n    image: x?.image?.imageUrl ? { imageUrl: String(x.image.imageUrl) } : null,\n    itemLocation: x?.itemLocation || null\n  })) : [];\n\n  return json({\n    ok:true,\n    source:"eBay Browse API · active EBAY_GB listings",\n    evidenceType:"current_active_asking_prices",\n    query,\n    identity:{ cardName, cardNumber, setName, language, grader, grade },\n    total:Number(ebay.data?.total || itemSummaries.length || 0),\n    itemSummaries\n  });\n}\n\n'''
s=s.replace(marker,block+marker,1)
route_marker='} else if (url.pathname === "/api/ebay/status" && request.method === "GET") {'
if route_marker not in s:
    raise SystemExit('router marker missing')
route='} else if (url.pathname === "/api/ebay/graded-market" && request.method === "POST") {\n        response = await handleGradedMarket(request, env);\n      '
s=s.replace(route_marker,route+route_marker,1)
p.write_text(s)
